spring:
  application:
    name: user-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:9000

    gcp:
      project-id: impactful-study-477106-j6
      credentials:
        location: classpath:credentials/impactful-study-477106-j6-0f645b3d3bcd.json


app:
  gcp:
    bucket: cams-project-cloud-storage
