spring:
  application:
    name: user-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://config.platform:9000

    gcp:
      project-id: impactful-study-477106-j6



app:
  gcp:
    bucket: cams-project-cloud-storage
